name: trigger-tekton
on:
  push:
    paths:
      - 'Containerfile'
jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Semver Github Action
        uses: bitjuice-net/actions-semver@v1.0.4
  
      - name: Trigger Tekton Webhook      
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "ref": "${{ github.ref }}",
            "repository": {
              "git_url": "https://github.com/${{ github.repository }}.git",
              "url": "https://github.com/${{ github.repository }}",
              "name": "${{ github.repository }}"
            },
            "pusher": {
              "name": "${{ github.actor }}"
            },
            "head_commit": {
              "id": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}",
              "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            }
          }' ${{ secrets.TEKTON_WEBHOOK }}

      - name: notification
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: |
            "${{ github.repository }}": changes to source directory detected<br />
            **Tekton pipeline triggered**<br />
            commit message: **${{ github.event.head_commit.message }}** <br />
            contributor: **${{ github.actor }}** <br />
            commit sha: **${{ github.sha }}** <br />
            commit history: **[link](https://github.com/${{ github.repository }}/commits/main)** <br />
            Pipeline: **[link](https://console-openshift-console.apps.ocp.michard.cc/pipelines/ns/build-environment)** <br />